# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/Cpp-6

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/Cpp-6

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/Cpp-6/CMakeFiles /root/Cpp-6//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/Cpp-6/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pro2

# Build rule for target.
pro2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pro2
.PHONY : pro2

# fast build rule for target.
pro2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pro2.dir/build.make CMakeFiles/pro2.dir/build
.PHONY : pro2/fast

src/AlgebraicExpreWork.o: src/AlgebraicExpreWork.cpp.o
.PHONY : src/AlgebraicExpreWork.o

# target to build an object file
src/AlgebraicExpreWork.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pro2.dir/build.make CMakeFiles/pro2.dir/src/AlgebraicExpreWork.cpp.o
.PHONY : src/AlgebraicExpreWork.cpp.o

src/AlgebraicExpreWork.i: src/AlgebraicExpreWork.cpp.i
.PHONY : src/AlgebraicExpreWork.i

# target to preprocess a source file
src/AlgebraicExpreWork.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pro2.dir/build.make CMakeFiles/pro2.dir/src/AlgebraicExpreWork.cpp.i
.PHONY : src/AlgebraicExpreWork.cpp.i

src/AlgebraicExpreWork.s: src/AlgebraicExpreWork.cpp.s
.PHONY : src/AlgebraicExpreWork.s

# target to generate assembly for a file
src/AlgebraicExpreWork.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pro2.dir/build.make CMakeFiles/pro2.dir/src/AlgebraicExpreWork.cpp.s
.PHONY : src/AlgebraicExpreWork.cpp.s

src/MathematicalWork.o: src/MathematicalWork.cpp.o
.PHONY : src/MathematicalWork.o

# target to build an object file
src/MathematicalWork.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pro2.dir/build.make CMakeFiles/pro2.dir/src/MathematicalWork.cpp.o
.PHONY : src/MathematicalWork.cpp.o

src/MathematicalWork.i: src/MathematicalWork.cpp.i
.PHONY : src/MathematicalWork.i

# target to preprocess a source file
src/MathematicalWork.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pro2.dir/build.make CMakeFiles/pro2.dir/src/MathematicalWork.cpp.i
.PHONY : src/MathematicalWork.cpp.i

src/MathematicalWork.s: src/MathematicalWork.cpp.s
.PHONY : src/MathematicalWork.s

# target to generate assembly for a file
src/MathematicalWork.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pro2.dir/build.make CMakeFiles/pro2.dir/src/MathematicalWork.cpp.s
.PHONY : src/MathematicalWork.cpp.s

src/NumToString.o: src/NumToString.cpp.o
.PHONY : src/NumToString.o

# target to build an object file
src/NumToString.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pro2.dir/build.make CMakeFiles/pro2.dir/src/NumToString.cpp.o
.PHONY : src/NumToString.cpp.o

src/NumToString.i: src/NumToString.cpp.i
.PHONY : src/NumToString.i

# target to preprocess a source file
src/NumToString.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pro2.dir/build.make CMakeFiles/pro2.dir/src/NumToString.cpp.i
.PHONY : src/NumToString.cpp.i

src/NumToString.s: src/NumToString.cpp.s
.PHONY : src/NumToString.s

# target to generate assembly for a file
src/NumToString.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pro2.dir/build.make CMakeFiles/pro2.dir/src/NumToString.cpp.s
.PHONY : src/NumToString.cpp.s

src/PolynomialWork.o: src/PolynomialWork.cpp.o
.PHONY : src/PolynomialWork.o

# target to build an object file
src/PolynomialWork.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pro2.dir/build.make CMakeFiles/pro2.dir/src/PolynomialWork.cpp.o
.PHONY : src/PolynomialWork.cpp.o

src/PolynomialWork.i: src/PolynomialWork.cpp.i
.PHONY : src/PolynomialWork.i

# target to preprocess a source file
src/PolynomialWork.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pro2.dir/build.make CMakeFiles/pro2.dir/src/PolynomialWork.cpp.i
.PHONY : src/PolynomialWork.cpp.i

src/PolynomialWork.s: src/PolynomialWork.cpp.s
.PHONY : src/PolynomialWork.s

# target to generate assembly for a file
src/PolynomialWork.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pro2.dir/build.make CMakeFiles/pro2.dir/src/PolynomialWork.cpp.s
.PHONY : src/PolynomialWork.cpp.s

src/StringToNum.o: src/StringToNum.cpp.o
.PHONY : src/StringToNum.o

# target to build an object file
src/StringToNum.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pro2.dir/build.make CMakeFiles/pro2.dir/src/StringToNum.cpp.o
.PHONY : src/StringToNum.cpp.o

src/StringToNum.i: src/StringToNum.cpp.i
.PHONY : src/StringToNum.i

# target to preprocess a source file
src/StringToNum.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pro2.dir/build.make CMakeFiles/pro2.dir/src/StringToNum.cpp.i
.PHONY : src/StringToNum.cpp.i

src/StringToNum.s: src/StringToNum.cpp.s
.PHONY : src/StringToNum.s

# target to generate assembly for a file
src/StringToNum.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pro2.dir/build.make CMakeFiles/pro2.dir/src/StringToNum.cpp.s
.PHONY : src/StringToNum.cpp.s

src/WrongDialog.o: src/WrongDialog.cpp.o
.PHONY : src/WrongDialog.o

# target to build an object file
src/WrongDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pro2.dir/build.make CMakeFiles/pro2.dir/src/WrongDialog.cpp.o
.PHONY : src/WrongDialog.cpp.o

src/WrongDialog.i: src/WrongDialog.cpp.i
.PHONY : src/WrongDialog.i

# target to preprocess a source file
src/WrongDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pro2.dir/build.make CMakeFiles/pro2.dir/src/WrongDialog.cpp.i
.PHONY : src/WrongDialog.cpp.i

src/WrongDialog.s: src/WrongDialog.cpp.s
.PHONY : src/WrongDialog.s

# target to generate assembly for a file
src/WrongDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pro2.dir/build.make CMakeFiles/pro2.dir/src/WrongDialog.cpp.s
.PHONY : src/WrongDialog.cpp.s

src/add.o: src/add.cpp.o
.PHONY : src/add.o

# target to build an object file
src/add.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pro2.dir/build.make CMakeFiles/pro2.dir/src/add.cpp.o
.PHONY : src/add.cpp.o

src/add.i: src/add.cpp.i
.PHONY : src/add.i

# target to preprocess a source file
src/add.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pro2.dir/build.make CMakeFiles/pro2.dir/src/add.cpp.i
.PHONY : src/add.cpp.i

src/add.s: src/add.cpp.s
.PHONY : src/add.s

# target to generate assembly for a file
src/add.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pro2.dir/build.make CMakeFiles/pro2.dir/src/add.cpp.s
.PHONY : src/add.cpp.s

src/mul.o: src/mul.cpp.o
.PHONY : src/mul.o

# target to build an object file
src/mul.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pro2.dir/build.make CMakeFiles/pro2.dir/src/mul.cpp.o
.PHONY : src/mul.cpp.o

src/mul.i: src/mul.cpp.i
.PHONY : src/mul.i

# target to preprocess a source file
src/mul.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pro2.dir/build.make CMakeFiles/pro2.dir/src/mul.cpp.i
.PHONY : src/mul.cpp.i

src/mul.s: src/mul.cpp.s
.PHONY : src/mul.s

# target to generate assembly for a file
src/mul.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pro2.dir/build.make CMakeFiles/pro2.dir/src/mul.cpp.s
.PHONY : src/mul.cpp.s

src/pro2.o: src/pro2.cpp.o
.PHONY : src/pro2.o

# target to build an object file
src/pro2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pro2.dir/build.make CMakeFiles/pro2.dir/src/pro2.cpp.o
.PHONY : src/pro2.cpp.o

src/pro2.i: src/pro2.cpp.i
.PHONY : src/pro2.i

# target to preprocess a source file
src/pro2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pro2.dir/build.make CMakeFiles/pro2.dir/src/pro2.cpp.i
.PHONY : src/pro2.cpp.i

src/pro2.s: src/pro2.cpp.s
.PHONY : src/pro2.s

# target to generate assembly for a file
src/pro2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pro2.dir/build.make CMakeFiles/pro2.dir/src/pro2.cpp.s
.PHONY : src/pro2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... pro2"
	@echo "... src/AlgebraicExpreWork.o"
	@echo "... src/AlgebraicExpreWork.i"
	@echo "... src/AlgebraicExpreWork.s"
	@echo "... src/MathematicalWork.o"
	@echo "... src/MathematicalWork.i"
	@echo "... src/MathematicalWork.s"
	@echo "... src/NumToString.o"
	@echo "... src/NumToString.i"
	@echo "... src/NumToString.s"
	@echo "... src/PolynomialWork.o"
	@echo "... src/PolynomialWork.i"
	@echo "... src/PolynomialWork.s"
	@echo "... src/StringToNum.o"
	@echo "... src/StringToNum.i"
	@echo "... src/StringToNum.s"
	@echo "... src/WrongDialog.o"
	@echo "... src/WrongDialog.i"
	@echo "... src/WrongDialog.s"
	@echo "... src/add.o"
	@echo "... src/add.i"
	@echo "... src/add.s"
	@echo "... src/mul.o"
	@echo "... src/mul.i"
	@echo "... src/mul.s"
	@echo "... src/pro2.o"
	@echo "... src/pro2.i"
	@echo "... src/pro2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

